

version: '3'

services:
  traefik1:
    image: traefik:alpine
    restart: always
    container_name: traefik1
    ports:
      - "8081:8081"
      - "443:443"
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro
      - ./acme.json:/acme.json
      - ./certs:/certs
    networks:
      - proxy
    labels:
     - traefik.frontend.rule:=Host:traffic.clouds.net
     - traefik.enable=true
     - traefik.port=8080
     - traefik.docker.network=proxy 
     - traefik.frontend.entryPoints=http,https

    command:
      - --entrypoints=Name:https Address::443 TLS


  portainer:
    image: portainer/portainer
    networks:
      - proxy
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=9000
      - traefik.frontend.rule=Host:portainer.clouds.net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /opt/prometheus/conf:/etc/prometheus
      - /opt/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    
    networks:
      - proxy
    
    labels:
     - traefik.port=9090
     - traefik.front.rule=Host:cloud.clouds.net
     - traefik.enable=true
     - traefik.default.protocol=http

  node-exporter:
    image: prom/node-exporter
    container_name: nodeprom
    ports:
     - '9100:9100'
    labels:
  
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=9100
      - traefik.frontend.rule=Host:node.clouds.net

  grafana:
    image: grafana/grafana
    container_name: grafa

    volumes: 
      - /opt/grafana_data:/var/lib/grafana:rw
    ports:
     - "3000:3000"
    labels:
  
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.frontend.rule=Host:grafana.clouds.net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin007
      - GF_PATHS_LOGS=/var/logs/grafana
      - GF_SERVER_ROOT_URL=http://grafana.clouds.net:3000

    depends_on:
      - prometheus  
  
  jenkins: 

    image: bitnami/jenkins:latest
    container_name: jenks
    volumes:
     - ./jenkins_data:/bitnami
     - ./home:/home
    environment:
     - JENKINS_PASSWORD=toor89
     - JENKINS_USERNAME=admin
     
    
    ports:
      - "8080"
      - "8443"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=8080
      - traefik.frontend.rule=Host:jenkins.clouds.net
    networks:
      - proxy
    

networks:
  proxy:
    external: true
  web:
    external: false


volumes:
  portainer-data:
    external: true
