

version: '3'

services:
  nginx:
    container_name: moby_cock
    image: nginx:latest
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
      - ./html1:/usr/share/nginx/html1:ro
      - ./html2:/usr/share/nginx/html2:ro

    ports:
      - "80:80"  
      - "443:443"
      - "8080:8080"
      - "8081:8081"
    networks:
      - assnet

networks:
  assnet:
