

---

 
- hosts: clientcloud.zekloud.net
  become: yes
  become_user: root
  tasks:
   - name: Install Mariadb
     yum: 
      name: mariadb-server
      state: installed
      update_cache: true
   
