#!/bin/bash


resolv="etc/resolv.conf"

sudo chattr -i ${resolv}



echo "# Generated by NetworkManager" > ${resolv}
echo "search home zekloud.net" >> ${resolv}
echo "nameserver 10.1.1.1" >> ${resolv}
